name: Test

on:
  pull_request:
    types: [opened, reopened]

jobs:
  test:
    name: Test
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v3
        with:
          # This makes Actions fetch all Git history so that Changesets can generate changelogs with the correct commits
          fetch-depth: 0

      - uses: pnpm/action-setup@v2.2.1
        with:
          version: 7.0.0-rc.6
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
          cache: "pnpm"
      - name: Install dependencies
        run: pnpm install

      - name: Run tests on apps/web
        uses: codecov/codecov-action@v3.1.0
        run: cd apps/web && pnpm run test:coverage
        with:
          files: apps/web/coverage.json
          name: codecov-umbrella # optional
          verbose: true # optional (default = false)